module.exports = {
	NEW_ROOMS: "New Rooms",
	ROOM_CHANGE: "Room Change",
	PLAYER_COUNT: "online player count change",
	LOGIN_COMPLETE: "login complete",
	EXPAND_QUESTIONS: "expandLibrary questions",
	PLAYER_PROFILE: "player profile",
	LEADERBOARD: "all leaderboard level entries",
	SELF_LEADERBOARDS: "self leaderboard level entries",
	TOP_LEADERBOARDS: "top leaderboard level entries",
	FRIENDS_LEADERBOARDS: "friends leaderboard level entries",
	HOST_GAME: "Host Game",
	JOIN_GAME: "Join Game",
	SPECTATE_GAME: "Spectate Game",
	AVATAR_DRIVE_STANDINGS: "avatar drive standings",
	PATREON_CHANGED: "patreon changed",
	USE_AVATAR: "use avatar",
	OUTFIT_DESIGNS: "get outfit designs",
	LEAVE_GAME_QUEUE: "leave game queue",
	JOIN_GAME_QUEUE: "join game queue",
	GET_SONG_NAMES: "get all song names",
	UPDATE_SONG_NAMES: "update all song names",
	SAVE_QUIZ_SETTINGS: "save quiz settings",
	ALL_ONLINE_USERS: "all online users",
	ANSWER_RESULTS: "answer results",
	GAME_STARTING: "Game Starting",
	QUIZ_NEXT_VIDEO_INFO: "quiz next video info",
	QUIZ_END_RESULT: "quiz end result",
	PLAY_NEXT_SONG: "play next song",
	NEW_DONATION: "new donation",
	AVATAR_DRIVE_CHANGES: "avatar drive changes",
	FREE_AVATAR_DONATION: "free avatar donation",
	UNLOCK_AVATAR: "unlock avatar",
	EXPAND_SONG_ANSWERED: "expandLibrary song answered",
	EXPAND_ANSWER: "expandLibrary answer",
	BATTLE_ROYAL_READY: "battle royal ready",
	BATTLE_ROYAL_SPAWN: "battle royal spawn",
	BATTLE_ROYAL_OBJECT_DESPAWN: "battle royal object despawn",
	BATTLE_ROYAL_ENTRY_COLLECTED: "new collected name entry",
	BATTLE_ROYAL_DATA_STORE_CONTENT: "battle royal data store content",
	BATTLE_ROYAL_CONTAINER_ENTRY_DESPAWN: "container entry despawn",
	BATTLE_ROYAL_SPAWN_PLAYER: "battle royal spawn player",
	BATTLE_ROYAL_NEW_PLAYER_POSITION: "battle royal new player position",
	BATTLE_ROYAL_PLAYER_DESPAWN: "battle royal despawn player",
	BATTLE_ROYAL_PHASE_OVER: "battle royal phase over",
	BATTLE_ROYAL_CORRECT_POSITION: "battle royale correct posistion",
	BATTLE_ROYAL_TILE_COUNT: "battle royal tile count",
	BATTLE_ROYAL_TILE_SPECTATOR_COUNT: "tile spectator count change",
	BATTLE_ROYAL_RETURN_MAP: "battle royal return map",
	BATTLE_ROYAL_DROP_NAME_ENTRY: "drop name entry",
	BATTLE_ROYAL_OBJECT_SPAWN: "battle royal object spawn",
	PLAYER_NAME_CHANGE: "player name change",
	SPECTATOR_NAME_CHANGE: "spectator name change",
	PLAYER_LEFT: "Player Left",
	GAME_CHAT_MESSAGE: "Game Chat Message",
	NEW_SPECTATOR: "New Spectator",
	SPECTATOR_LEFT: "Spectator Left",
	SPECTATOR_CHANGED_TO_PLAYER: "Spectator Change To Player",
	KICKED_FROM_GAME: "Kicked From Game",
	PLAYER_CHANGED_TO_SPECTATOR: "Player Changed To Spectator",
	ROOM_SETTINGS_CHANGED: "Room Settings Changed",
	NEW_PLAYER_IN_GAME_QUEUE: "new player in game queue",
	PLAYER_LEFT_QUEUE: "player left queue",
	HOST_PROMOTION: "Host Promotion",
	DELETE_PLAYER_MESSAGES: "delete player messages",
	DELETE_CHAT_MESSAGES: "delete chat message",
	NEW_PLAYER: "New Player",
	PLAYER_READY_CHANGE: "Player Ready Change",	
	AVATAR_CHANGE: "avatar change",
	GAME_CLOSED: "game closed",
	QUIZ_NO_SONGS: "Quiz no songs",
	QUIZ_OVER: "quiz over",
	QUIZ_SEND_FEEDBACK: "send feedback",
	QUIZ_REJOINING_PLAYER: "Rejoining Player",
	QUIZ_READY: "quiz ready",
	QUIZ_PLAYER_ANSWERS: "player answers",
	QUIZ_WAITING_BUFFERING: "quiz waiting buffering",
	QUIZ_XP_CREDIT_GAIN: "quiz xp credit gain",
	QUIZ_NO_PLAYERS: "quiz no players",
	QUIZ_PLAYER_ANSWERED: "player answered",
	QUIZ_OVERLAY_MESSAGE: "quiz overlay message",
	QUIZ_SKIP_MESSAGE: "quiz skip message",
	QUIZ_RETURN_LOBBY_VOTE_START: "return lobby vote start",
	QUIZ_GUESS_PHASE_OVER: "guess phase over",
	QUIZ_FATAL_ERROR: "quiz fatal error",
	QUIZ_ANSWER: "quiz answer",
	QUIZ_RETURN_LOBBY_VOTE_RESULT: "return lobby vote result",
	QUIZ_SETTING_DELETED: "quiz setting deleted",
	QUIZ_SAVE_SETTINGS: "save quiz settings",
	RANKED_STANDING_UPDATED: "ranked standing updated",
	RANKED_CHAMPIONS_UPDATED: "ranked champions updated",
	RANKED_GAME_STATE_CHANGE: "ranked game state change",
	COMPLETED_TUTORIAL: "completed tutorial",
	ONLINE_USER_CHANGE: "online user change",
	ALL_PLAYER_NAME_CHANGE: "all player name change",
	NEW_FRIEND_REQUEST_RECEIVED: "new friend request recived",
	GAME_INVITE: "game invite",
	NEW_CHAT_ALERT: "new chat alert",
	CHAT_MESSAGE: "chat message",
	SERVER_MESSAGE: "server message",
	PLAYER_ONLINE_CHANGE: "player online change",
	CHAT_MESSAGE_RESPONSE: "chat message response",
	NEW_FRIEND: "new friend",
	FRIEND_STATE_CHANGE: "friend state change",
	FRIEND_NAME_CHANGE: "friend name change",
	FRIEND_REQUEST: "friend request",
	XP_CREDIT_CHANGE: "xp credit change",
	EMOJI_DELETED: "emoji deleted",
	EMOJI_APPROVED: "emoji approved",
	MAL_LAST_UPDATE: "malLastUpdate update",
	ANILIST_LAST_UPDATE: "aniListLastUpdate update",
	KITSU_LAST_UPDATE: "kitsuLastUpdate update",
	MAL_UPDATE_RESULT: "mal update result",
	ANILIST_UPDATE_RESULT: "anime list update result",
	CLEAR_MAL: "clear mal",
	SERVER_STATE_CHANGED: "server state change",
	FORCED_LOGOFF: "force logoff",
	ALERT: "alert",
	UNKNOWN_ERROR: "unknown error",
	SERVER_RESTART: "server restart",
	POPOUT_MESSAGE: "popout message",
	RANKED_SCORE_UPDATE: "ranked score update",
	ALL: "*"
}